// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/themes/DarkMode.tsx": () => import("../components/mockups/themes/DarkMode.tsx"),
  "./components/mockups/themes/ForestGreen.tsx": () => import("../components/mockups/themes/ForestGreen.tsx"),
  "./components/mockups/themes/OceanBlue.tsx": () => import("../components/mockups/themes/OceanBlue.tsx"),
  "./components/mockups/themes/WarmAmber.tsx": () => import("../components/mockups/themes/WarmAmber.tsx")
};
